
package service;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AdminServiceImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:10020/AdminService?wsdl")
public class AdminServiceImplServiceKKL
        extends Service {

    private final static URL ADMINSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ADMINSERVICEIMPLSERVICE_QNAME = new QName("http://service/", "AdminServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10020/AdminService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ADMINSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AdminServiceImplServiceKKL() {
        super(__getWsdlLocation(), ADMINSERVICEIMPLSERVICE_QNAME);
    }

    public AdminServiceImplServiceKKL(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminServiceImplServiceKKL(URL wsdlLocation) {
        super(wsdlLocation, ADMINSERVICEIMPLSERVICE_QNAME);
    }

    public AdminServiceImplServiceKKL(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminServiceImplServiceKKL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminServiceImplServiceKKL(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort() {
        return super.getPort(new QName("http://service/", "AdminServicePort"), AdminService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AdminServicePort"), AdminService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw ADMINSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ADMINSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
