
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentServiceImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:10010/StudentService?wsdl")
public class StudentServiceImplServiceDVL
    extends Service
{

    private final static URL STUDENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName STUDENTSERVICEIMPLSERVICE_QNAME = new QName("http://service/", "StudentServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10010/StudentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        STUDENTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public StudentServiceImplServiceDVL() {
        super(__getWsdlLocation(), STUDENTSERVICEIMPLSERVICE_QNAME);
    }

    public StudentServiceImplServiceDVL(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public StudentServiceImplServiceDVL(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSERVICEIMPLSERVICE_QNAME);
    }

    public StudentServiceImplServiceDVL(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSERVICEIMPLSERVICE_QNAME, features);
    }

    public StudentServiceImplServiceDVL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServiceImplServiceDVL(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServicePort")
    public StudentService getStudentServicePort() {
        return super.getPort(new QName("http://service/", "StudentServicePort"), StudentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServicePort")
    public StudentService getStudentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "StudentServicePort"), StudentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw STUDENTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return STUDENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
